# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9012
# 日志配置
logging:
  level:
    com.pfdl.js.mapper: debug
    org.springframework: warn
# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # redis 配置
  redis:
    # 地址
    host: 192.168.1.162
    # 端口，默认为6379
    port: 6001
    # 密码
    password: 
    # 连接超时时间
    timeout: 15s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.pfdl.api.jdbc
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
# PageHelper分页插件
pagehelper: 
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
#桩自动停止充电调用后端服务地址
ServiceAddress:
  url: http://192.168.1.167:40000/order/refundContro
